name: 'app'
type: 'php:7.2'

relationships:
    mysql: 'mysql:drupal'

#        solr: 'solrsearch:solr'
#        redis: 'rediscache:redis'

disk: 2048

mounts:
    '/web/sites/default/files': 'shared:files/files-public'
    '/tmp': 'shared:files/tmp'
    '/private': 'shared:files/files-private'
    '/.drush': 'shared:files/.drush'
    '/drush-backups': 'shared:files/drush-backups'

build:
    flavor: none

hooks:
    build: |
        set -e
        echo -e 'Installing platform.sh cli client'
        curl -sS https://platform.sh/cli/installer | php

        echo -e 'Building drupal'
        cd /app
        composer install --prefer-dist --no-interaction

        # echo -e 'Building pattern lab'
        # cd /app
        # composer install --prefer-dist -d web/themes/custom/autheme/patternlab
        # composer generate -d web/themes/custom/autheme/patternlab
        # npm install --prefix web/themes/custom/autheme
        # chmod 755 web/themes/custom/autheme/patternlab/public/index.html

    deploy: |
        set -e
        cd /app/web
        drush -y -l default cache-rebuild
        drush -y -l default updatedb
        drush -y -l default config-import
        drush -y -l default entup || true;

web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            root: 'web'
            # How long to allow static assets from this location to be cached.
            expires: 5m
            passthru: '/index.php'
            # Deny access to static files in this location.
            allow: false
            rules:
                # Allow access to common static files.
                '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
                    allow: true
                '^/robots\.txt$':
                    allow: true
                '^/sitemap\.xml$':
                    allow: true

                # Deny direct access to configuration files.
                '^/sites/sites\.php$':
                    scripts: false
                '^/sites/[^/]+/settings.*?\.php$':
                    scripts: false

        '/sites/default/files':
            root: 'web/sites/default/files'
            expires: 5m
            passthru: '/index.php'
            allow: true
            # Do not execute PHP scripts.
            scripts: false
            rules:
                # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
                '^/sites/default/files/(css|js)':
                    expires: 2w

# The configuration of scheduled execution.
crons:
    snapshot:
        spec: '0 18 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                    platform snapshot:create --yes --no-wait
            fi
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd web ; drush core-cron'
