version: '3'

# This extends Lando.

services:
  chrome:
    image: previousnext/chrome-headless:65
    ports:
      - "9222:9222"

  # See https://github.com/SeleniumHQ/docker-selenium/tree/master/StandaloneChrome
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
