mysql:
  type: mysql:10.2
  disk: 2048
  configuration:
    schemas:
      - drupal
    endpoints:
      drupal:
        default_schema: drupal
        privileges:
          drupal: admin

#
#rediscache:
#    type: redis:3.2
#
#solrsearch:
#    type: solr:6.6
#    disk: 1024
